spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/hfinance_system
spring.datasource.username=postgres
spring.datasource.password=061966
spring.datasource.driver-class-name=org.postgresql.Driver

# 5. Ch? ?? t? ??ng sinh/c?p nh?t b?ng t? Class Entity Java vào DB
spring.jpa.hibernate.ddl-auto=update

# 6. B?t tính n?ng in các câu l?nh SQL mà Hibernate t? sinh ra xu?ng màn hình Console
spring.jpa.show-sql=true

# 7. ??nh d?ng câu l?nh SQL cho xu?ng dòng, d? ??c (Thay vì in trên 1 dòng dài lê thê)
spring.jpa.properties.hibernate.format_sql=true

# 8. Ch? ??nh ?úng ngôn ng? (Dialect) c?a PostgreSQL ?? Hibernate t?i ?u câu l?nh SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect