spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/hfinance_system
spring.datasource.username=postgres
spring.datasource.password=061966
spring.datasource.driver-class-name=org.postgresql.Driver

# 5. Ch? ?? t? ??ng sinh/c?p nh?t b?ng t? Class Entity Java v�o DB
spring.jpa.hibernate.ddl-auto=update

# 6. B?t t�nh n?ng in c�c c�u l?nh SQL m� Hibernate t? sinh ra xu?ng m�n h�nh Console
spring.jpa.show-sql=true

# 7. ??nh d?ng c�u l?nh SQL cho xu?ng d�ng, d? ??c (Thay v� in tr�n 1 d�ng d�i l� th�)
spring.jpa.properties.hibernate.format_sql=true

# 8. Ch? ??nh ?�ng ng�n ng? (Dialect) c?a PostgreSQL ?? Hibernate t?i ?u c�u l?nh SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect