spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/hfinance_system
spring.datasource.username=postgres
spring.datasource.password=061966
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Kh�a b� m?t d�ng ?? m� h�a m� JWT (Ph?i d�i t?i thi?u 256-bit / 32 k� t?)
app.jwt.secret=HFinanceSystemSecretKey2026SecureAndLongEnoughForHS256Algorithm
# Th?i gian h?t h?n c?a Token (V� d?: 300000 ms =5p)
app.jwt.expiration-milliseconds=86400000
